version: "3.8"
services:
  postgres:
    container_name: titter-postgres
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
     - ./data:/var/lib/postgresql/data
     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d